travis:
  secure:
    BINSTAR_TOKEN: cGZbp3tEVMYpzc2ReODX08PQ7EcZSoeTiJMYhPLOS5g+3wOYj1WaHLaBOIMPSuSR+ZSsV3uDNTfnMwJaJGzdVjPOJcAZLVRI3z1FVmrbDkVf+A1nolJieZzVUQYRz1NUHtIlWVCIKv5cgbPyMfXYgScme49us9nI2yq8qITUWh/BqNMkN3GALqkqE5fMaEP3HX9kFptxjFtWlyXfbK+vAEI1yQJU4jjLsqeDHSoMhU1R2dXAzPxC6EYu64OjvRvwfRQHENu9oYlp6nTydIlMBVq7NvEqo8gdkFyTvrmchrTD6yuQE3GzCbt4ugL2q0XoSOnBxsezF/6nA+xQU4SEEpVIHLwStEB8sJSql9FppAcpZ8HUejGDuVzGYo/otAlgTeyPQ2VCcKzDF+aP04hyt++3tO2r5cAOYx8cg9Vg8+/Re40MaX3hpW1JkkFoh0jFjv/9gbQJVLobDCimcHEocYxaL1cVGBbb7MVRA9B7fv764YhmijUqUJAjWLY1UxLbuoz2I/n2OvupvkttuPWQeR+UVMloHTljb+GtdvSbpO8mLaHLd9ci7fTw52b06nEuvolX/aAEdPUYK8PF/M79eMDcgHC81+oQiKq7jrACjoXGNCxFPQXHACzOHf5E8YBs6QTRNyNURWRMSM8baI37/7VGCWpYQeiUT3qocnbJlak=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
