travis:
  secure:
    BINSTAR_TOKEN: uGW2atAGlIkFzrZi5CnWII+6mJuUuC6ytOqBEMiGaNzM3JgauaLuzJmudakaWp10BjZaJ3Kz1hoAjj5y6531mm45tRKS7YAn6f4RKDVKqiVPihSejIxiOwtM1dKCyFSoLNSIQFYBT0OG8+5Nv3//aPDU+BCTdskdbjn9amLN7QP+EhSJOA5obCsJkIwrZ7t52RXZgHgoysWzi27z3Yxwm8XEZuZmO9NrQgPrefnoxZ3F1Pq+cHoyarSrpB7d3353Ey8e60OCH+Ll+XGIoOl002O0JhqtBd22h/F4+VCv6mwJa5szHYtePMsJb6iXjHnD8Bi2Ig2tnnKmE+mW3utlJCNikIGLfjlGcA/Tzuq/0GLVyq+j2S1MvGRvMlCl2SmBvfmHKYMGH7lLGB4fWow+0AzyxRclKSK0gLyQYFytL61EcTqzxUQ/1TZyIoOSYM5hI5tQ3SmNE42ycRV21B811JunppDqBWOIY82Nh6qe9Qq5IUC5h79eWEYCgWzrZENQxTwTtsmWmxJ7G9ShYHvhY4Bbcz6Osjs1PlU59e+kAG29W2mUoze5FEhEh5fSj+eKX7WbNgbJzM78UNsQpnwgIrKewLj0s6mtNG3cO2DLcVVy+KXFCus9oMXifm1eotyn7IRrHXRUK6ToXYuIhB4DyNyguoaQZuFJupKX2KpVfEM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
